version = 0.1

[default.global.parameters]
stack_name = "core-account-subscription-purchase-role"
s3_bucket = "mytiki-core-ocean-cf-deploy"
s3_prefix = "core/aws/account/subscription/purchase/role"
region = "us-east-2"

[default.deploy.parameters]
confirm_changeset = false
capabilities = [
    "CAPABILITY_IAM",
    "CAPABILITY_NAMED_IAM",
    "CAPABILITY_AUTO_EXPAND"
]
image_repositories = []
parameter_overrides = []
